# ====================================================================================================
#   H2 인 메모리 DB를 사용하는 개발 환경
# ====================================================================================================

server:
  port: 80

spring:
  # 데이터베이스 연결 정보 설정 : H2 인 메모리 DB
  datasource:
    url: ${DEV_DB_URL}
    driver-class-name: ${DEV_DB_DRIVER}
    username: ${DEV_DB_USERNAME}
  sql:
    # SQL 초기화 설정
    init:
      encoding: UTF-8
      # 내장 데이터베이스 사용시 SQL 스크립트 실행
      mode: embedded
      schema-locations:
        - classpath:sql/schema.sql
      data-locations:
        - classpath:sql/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true