
-- 작업 그룹 테이블 데이터 생성
INSERT INTO TASK_GROUPS (NAME, SORT, USED_YN, UPDATED_AT) VALUES ('기획 및 요구사항 분석', 1, 'Y', NOW());

INSERT INTO TASK_GROUPS (NAME, SORT, USED_YN, UPDATED_AT) VALUES ('시스템 설계', 2, 'Y', NOW());

INSERT INTO TASK_GROUPS (NAME, SORT, USED_YN, UPDATED_AT) VALUES ('구현', 3, 'Y', NOW());

INSERT INTO TASK_GROUPS (NAME, SORT, USED_YN, UPDATED_AT) VALUES ('테스트', 4, 'Y', NOW());

INSERT INTO TASK_GROUPS (NAME, SORT, USED_YN, UPDATED_AT) VALUES ('유지보수', 5, 'Y', NOW());

-- 게시판 그룹 테이블 데이터 생성
INSERT INTO BOARDS (NAME, DESCRIPTION, SORT, UPDATED_AT) VALUES ('공지사항', '없음', 1, NOW());

INSERT INTO BOARDS (NAME, DESCRIPTION, SORT, UPDATED_AT) VALUES ('자유게시판', '없음', 2, NOW());