DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP TABLE IF EXISTS PROFILES CASCADE;
DROP TABLE IF EXISTS LOGIN_HISTORIES CASCADE;


CREATE TABLE IF NOT EXISTS USERS COMMENT '사용자' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    EMAIL               VARCHAR(40)     NOT NULL,
    PASSWORD            VARCHAR(255)    NOT NULL,
    NICKNAME            VARCHAR(15)     NOT NULL,
    NAME                VARCHAR(15)     NOT NULL,
    PHONE               VARCHAR(11)     NOT NULL,
    AUTH_TYPE           VARCHAR(5)      NOT NULL COMMENT '일반 로그인 : BASIC / 소셜 로그인 : OAUTH'
    ENABLED             TINYINT(1)      NOT NULL,
    DELETED_YN          CHAR(1)         NOT NULL DEFAULT 'N',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    DELETED_AT          DATETIME        NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS USER_ROLES COMMENT '사용자 별 권한' (
    USER_ID             INT             NOT NULL,
    ROLE                VARCHAR(20)     NOT NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USER_ROLES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS PROFILES COMMENT '사용자 프로필' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    USER_ID             INT             NOT NULL,
    PROFILE_IMG_URL     VARCHAR(255)    NULL,
    BIO                 VARCHAR(150)    NULL,
    UNIV                VARCHAR(50)     NULL,
    LOCATION            VARCHAR(50)     NULL,
    SITE_URL            VARCHAR(255)    NULL,
    GITHUB_URL          VARCHAR(255)    NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PROFILES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS LOGIN_HISTORIES COMMENT '로그인 이력' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    USER_ID             INT             NOT NULL,
    IP_ADDRESS          VARCHAR(15)     NOT NULL,
    DEVICE              VARCHAR(8)      NOT NULL,
    OS                  VARCHAR(20)     NOT NULL,
    BROWSER             VARCHAR(20)     NOT NULL,
    CONN_STATUS         CHAR(1)         NOT NULL,
    LOGIN_AT            DATETIME        NOT NULL,
    LOGOUT_AT           DATETIME        NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_LOGIN_HISTORIES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);



DROP TABLE IF EXISTS TEAMS CASCADE;
DROP TABLE IF EXISTS TEAM_USERS CASCADE;


CREATE TABLE IF NOT EXISTS TEAMS COMMENT '팀' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    USER_ID             INT             NOT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    BIO                 VARCHAR(150)    NOT NULL,
    DELETED_YN          CHAR(1)         NOT NULL DEFAULT 'N',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    DELETED_AT          DATETIME        NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TEAMS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS TEAM_USERS COMMENT '팀원' (
    TEAM_ID             INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    IS_CAPTAIN          CHAR(1)         NOT NULL,
    PRIMARY KEY (TEAM_ID, USER_ID),
    CONSTRAINT FK_TEAM_USERS_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID),
    CONSTRAINT FK_TEAM_USERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);



DROP TABLE IF EXISTS PROJECTS CASCADE;
DROP TABLE IF EXISTS TASK_GROUPS CASCADE;
DROP TABLE IF EXISTS PROJECT_TASKS CASCADE;
DROP TABLE IF EXISTS TASK_ALLOCATIONS CASCADE;
DROP TABLE IF EXISTS TASK_ATTACHMENTS CASCADE;


CREATE TABLE IF NOT EXISTS PROJECTS COMMENT '프로젝트' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    TEAM_ID             INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    SUMMARY             VARCHAR(150)    NOT NULL,
    START_DATE          DATE            NOT NULL,
    END_DATE            DATE            NOT NULL,
    STATUS              CHAR(1)         NOT NULL,
    DELETED_YN          CHAR(1)         NOT NULL DEFAULT 'N',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    DELETED_AT          DATETIME        NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PROJECTS_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID),
    CONSTRAINT FK_PROJECTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS TASK_GROUPS COMMENT '업무 그룹' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    NAME                VARCHAR(50)     NOT NULL,
    ORDER_NO            INT             NULL,
    USED_YN             CHAR(1)         NOT NULL DEFAULT 'Y',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PROJECT_TASKS COMMENT '프로젝트 업무' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    PROJECT_ID          INT             NOT NULL,
    GROUP_ID            INT             NOT NULL,
    NAME                VARCHAR(150)    NOT NULL,
    START_DATE          DATE            NOT NULL,
    END_DATE            DATE            NOT NULL,
    ACTUAL_END_DATE     DATE            NULL,
    RATE                INT             NOT NULL DEFAULT 0,
    ORDER_NO            INT             NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PROJECT_TASKS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID),
    CONSTRAINT FK_PROJECT_TASKS_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES TASK_GROUPS (ID)
);


CREATE TABLE IF NOT EXISTS TASK_ALLOCATIONS COMMENT '프로젝트 업무 할당' (
    PROJECT_TASK_ID     INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    PRIMARY KEY (PROJECT_TASK_ID, USER_ID),
    CONSTRAINT FK_TASK_ALLOCATIONS_PROJECT_TASK_ID FOREIGN KEY (PROJECT_TASK_ID) REFERENCES PROJECT_TASKS (ID),
    CONSTRAINT FK_TASK_ALLOCATIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS TASK_ATTACHMENTS COMMENT '업무 산출물' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    PROJECT_TASK_ID     INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    FILE_NAME           VARCHAR(200)    NOT NULL,
    SAVED_PATH          VARCHAR(255)    NOT NULL,
    EXTENSION           VARCHAR(8)      NOT NULL,
    FILE_SIZE           INT             NOT NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_ATTACHMENTS_PROJECT_TASK_ID FOREIGN KEY (PROJECT_TASK_ID) REFERENCES PROJECT_TASKS (ID),
    FOREIGN KEY FK_TASK_ATTACHMENTS_USER_ID (USER_ID) REFERENCES USERS (ID)
);



DROP TABLE IF EXISTS MEETING_MINUTES CASCADE;
DROP TABLE IF EXISTS MEETING_ATTENDEES CASCADE;


CREATE TABLE IF NOT EXISTS MEETING_MINUTES COMMENT '회의록' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    PROJECT_ID          INT             NOT NULL,
    USER_ID             INT             NOT NULL COMMENT '회의록 작성자',
    MEETING_DATE        DATE            NOT NULL,
    TITLE               VARCHAR(150)    NOT NULL,
    CONTENTS            TEXT            NOT NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_MEETING_MINUTES_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID),
    CONSTRAINT FK_MEETING_MINUTES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS MEETING_ATTENDEES COMMENT '회의 참여자' (
    MEETING_ID          INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    PRIMARY KEY (MEETING_ID, USER_ID),
    CONSTRAINT FK_MEETING_ATTENDEES_MEETING_ID FOREIGN KEY (MEETING_ID) REFERENCES MEETING_MINUTES (ID),
    CONSTRAINT FK_MEETING_ATTENDEES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);



DROP TABLE IF EXISTS BOARD_GROUPS CASCADE;
DROP TABLE IF EXISTS POSTS CASCADE;
DROP TABLE IF EXISTS POST_LIKES CASCADE;
DROP TABLE IF EXISTS POST_ATTACHMENTS CASCADE;
DROP TABLE IF EXISTS COMMENTS CASCADE;


CREATE TABLE IF NOT EXISTS BOARD_GROUPS COMMENT '게시판 그룹' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    NAME                VARCHAR(40)     NOT NULL,
    ORDER_NO            INT             NULL,
    USED_YN             CHAR(1)         NOT NULL DEFAULT 'Y',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS POSTS COMMENT '게시글' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    GROUP_ID            INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    TITLE               VARCHAR(150)    NOT NULL,
    CONTENTS            TEXT            NOT NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_POSTS_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES BOARD_GROUPS (ID),
    CONSTRAINT FK_POSTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS POST_LIKES COMMENT '게시글 좋아요' (
    POST_ID             INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    PRIMARY KEY (POST_ID, USER_ID),
    CONSTRAINT FK_POST_LIKES_POST_ID FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    CONSTRAINT FK_POST_LIKES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
);


CREATE TABLE IF NOT EXISTS POST_ATTACHMENTS COMMENT '게시글 첨부 파일' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    POST_ID             INT             NOT NULL,
    ORIGINAL_NAME       VARCHAR(255)    NOT NULL,
    SAVED_PATH          VARCHAR(255)    NOT NULL,
    SAVED_NAME          VARCHAR(255)    NOT NULL,
    EXTENSION           VARCHAR(8)      NOT NULL,
    FILE_SIZE           INT             NOT NULL,
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_POST_ATTACHMENTS_POST_ID FOREIGN KEY (POST_ID) REFERENCES POSTS (ID)
);


CREATE TABLE IF NOT EXISTS COMMENTS COMMENT '댓글' (
    ID                  INT             NOT NULL AUTO_INCREMENT,
    POST_ID             INT             NOT NULL,
    USER_ID             INT             NOT NULL,
    PARENT_ID           INT             NULL,
    DEPTH               INT             NOT NULL,
    CONTENTS            VARCHAR(300)    NOT NULL,
    ORDER_NO            INT             NULL,
    DELETED_YN          CHAR(1)         NOT NULL DEFAULT 'N',
    CREATED_AT          DATETIME        NOT NULL DEFAULT NOW(),
    UPDATED_AT          DATETIME        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_COMMENTS_POST_ID FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    CONSTRAINT FK_COMMENTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_COMMENTS_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS (ID)
);