# ================================================================================
#   \uB85C\uADF8 \uD30C\uC77C \uAD00\uB828 \uC124\uC815
# ================================================================================
# \uB85C\uADF8 \uD30C\uC77C \uB514\uB809\uD1A0\uB9AC
LOG_DIR=logs
# \uD504\uB85C\uD30C\uC77C \uD658\uACBD\uBCC4 \uB85C\uADF8 \uD30C\uC77C \uACBD\uB85C
LOG_HOME=E:/dev/myapp/data/backup/
# \uB85C\uADF8 \uD30C\uC77C \uBA85
LOG_FILE_NAME=smate-application